In [26]:
from pathlib import Path

import geopandas as gpd

In [27]:
PROCESSED_DIR = Path("../data/processed")
PROCESSED_PATH = PROCESSED_DIR / "dnr_up_hiking_trails_grouped.parquet"

MICHIGAN_GEOREF = "EPSG:3078"
METERS_PER_MILE = 1609.344

trails = gpd.read_parquet(PROCESSED_PATH)

trails = gpd.GeoDataFrame(trails).copy()

epsg_code = trails.crs.to_epsg()

print(f"Source CRS: EPSG:{epsg_code}")

Source CRS: EPSG:4326

In [28]:
projected_trails = trails.to_crs(MICHIGAN_GEOREF)

epsg_code = projected_trails.crs.to_epsg()

print(f"Projected CRS: EPSG:{epsg_code}")

Projected CRS: EPSG:3078

In [34]:
projected_trails["GeospacialLength"] = (projected_trails.geometry.length / METERS_PER_MILE)

In [35]:
projected_trails.head(10)

,TrailGroupName,LengthCategory,HikingName,County,ReportedLengthMiles,TrailWidth,SurfaceTypes,AccessibilityValues,TrailStatuses,FacilityName,SegmentCount,geometry,GeospacialLength
0,Alger | Fox River Pathway,Long,Fox River Pathway,Alger,14.345076,0 To 2 Feet,Dirt Natural,Not Accessible,Open,State Forest,11,"MULTILINESTRING ((482473.921 670693.795, 48247...",14.345078
1,Alger | Laughing Whitefish Falls Trails,Medium,Laughing Whitefish Falls Trails,Alger,2.575298,0 To 2 Feet,Dirt Natural,Not Accessible,Open,SPRK422,17,"MULTILINESTRING ((417608.354 648542.593, 41760...",2.575299
2,Alger | North Country Trail,Long,North Country Trail,Alger,96.990313,Varies,"Concrete, Dirt Natural",Not Accessible,Open,SPRK422,129,"MULTILINESTRING ((504858.29 678975.86, 504874....",96.990289
3,Alger | Tyoga Historical Pathway,Short,Tyoga Historical Pathway,Alger,1.252893,0 To 2 Feet,Dirt Natural,Not Accessible,Open,State Forest,2,"MULTILINESTRING ((421071.54 662903.198, 421087...",1.252894
4,Alger | Wagner Falls Scenic Site - Foot Trail,Short,Wagner Falls Scenic Site - Foot Trail,Alger,0.125517,0 To 2 Feet,Dirt Natural,Not Accessible,Open,Wagner Falls Scenic Site,1,"LINESTRING (449931.179 648754.594, 449931.359 ...",0.125517
5,Baraga | Baraga Nature Trail,Short,Baraga Nature Trail,Baraga,0.570022,0 To 2 Feet,Dirt Natural,Not Accessible,Open,Baraga State Park,2,"MULTILINESTRING ((308878.917 693038.508, 30887...",0.570022
6,Baraga | Craig Lake Clair Lake Portage,Short,Craig Lake Clair Lake Portage,Baraga,0.262088,0 To 2 Feet,Dirt Natural,Not Accessible,Open,Craig Lake State Park,2,"MULTILINESTRING ((332675.613 676689.985, 33267...",0.262088
7,Baraga | Craig Lake Clair Lake Trail,Short,Craig Lake Clair Lake Trail,Baraga,1.343826,0 To 2 Feet,Dirt Natural,Not Accessible,Open,Craig Lake State Park,1,"LINESTRING (331930.091 675418.096, 331927.661 ...",1.343826
8,Baraga | Craig Lake Craig Lake Trail,Medium,Craig Lake Craig Lake Trail,Baraga,5.845377,0 To 2 Feet,Dirt Natural,Not Accessible,Open,Craig Lake State Park,45,"MULTILINESTRING ((332356.639 674508.148, 33236...",5.845378
9,Baraga | Craig Lake Crooked Lake Campsite Trail,Short,Craig Lake Crooked Lake Campsite Trail,Baraga,0.297381,0 To 2 Feet,Dirt Natural,Not Accessible,Open,Craig Lake State Park,1,"LINESTRING (333548.661 675098.467, 333550.751 ...",0.297381

In [38]:
(projected_trails["ReportedLengthMiles"].round(3) !=  projected_trails["GeospacialLength"].round(3)).sum()

np.int64(2)

In [39]:
projected_trails[(projected_trails["ReportedLengthMiles"].round(3) !=  projected_trails["GeospacialLength"].round(3))]

,TrailGroupName,LengthCategory,HikingName,County,ReportedLengthMiles,TrailWidth,SurfaceTypes,AccessibilityValues,TrailStatuses,FacilityName,SegmentCount,geometry,GeospacialLength
25,Delta | Days River Pathway,Long,Days River Pathway,Delta,11.590940,0 To 2 Feet,Dirt Natural,Not Accessible,Open,State Forest,22,"MULTILINESTRING ((418743.326 593889.087, 41875...",11.590493
47,Houghton | North Country Trail,Long,North Country Trail,Houghton,20.299796,Varies,Dirt Natural,Not Accessible,Open,Unknown,14,"MULTILINESTRING ((280265.482 681391.932, 28026...",20.298360